# Mutli CLass Image Classifier

## Better Result loss minimum and high accuarcy but predicting is not good. so that, we move on AlexNet

In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten,Conv2D, MaxPooling2D

Using TensorFlow backend.
c:\users\abhishek negi\.conda\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\abhishek negi\.conda\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\abhishek negi\.conda\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\abhis

In [2]:
model = Sequential()
# Select 6 feature convolution kernels with a size of 5 * 5 (without offset), and get 66 feature maps. The size of each feature map is 32−5 + 1 = 2832−5 + 1 = 28.
# That is, the number of neurons has been reduced from 10241024 to 28 ∗ 28 = 784 28 ∗ 28 = 784.
# Parameters between input layer and C1 layer: 6 ∗ (5 ∗ 5 + 1)
model.add(Conv2D(6, kernel_size=(5, 5), activation='relu', input_shape=(28, 28, 3)))
# The input of this layer is the output of the first layer, which is a 28 * 28 * 6 node matrix.
# The size of the filter used in this layer is 2 * 2, and the step length and width are both 2, so the output matrix size of this layer is 14 * 14 * 6.
model.add(MaxPooling2D(pool_size=(2, 2)))
# The input matrix size of this layer is 14 * 14 * 6, the filter size used is 5 * 5, and the depth is 16. This layer does not use all 0 padding, and the step size is 1.
# The output matrix size of this layer is 10 * 10 * 16. This layer has 5 * 5 * 6 * 16 + 16 = 2416 parameters
model.add(Conv2D(16, kernel_size=(5, 5), activation='relu'))
# The input matrix size of this layer is 10 * 10 * 16. The size of the filter used in this layer is 2 * 2, and the length and width steps are both 2, so the output matrix size of this layer is 5 * 5 * 16.
model.add(MaxPooling2D(pool_size=(2, 2)))
# The input matrix size of this layer is 5 * 5 * 16. This layer is called a convolution layer in the LeNet-5 paper, but because the size of the filter is 5 * 5, #
# So it is not different from the fully connected layer. If the nodes in the 5 * 5 * 16 matrix are pulled into a vector, then this layer is the same as the fully connected layer.
# The number of output nodes in this layer is 120, with a total of 5 * 5 * 16 * 120 + 120 = 48120 parameters.
model.add(Flatten())
model.add(Dense(120, activation='relu'))
# The number of input nodes in this layer is 120 and the number of output nodes is 84. The total parameter is 120 * 84 + 84 = 10164 (w + b)
model.add(Dense(84, activation='relu'))
# The number of input nodes in this layer is 84 and the number of output nodes is 4. The total parameter is 84 * 4 + 4 = 340
model.add(Dense(4, activation='softmax'))
# Compile
model.compile(loss=keras.metrics.categorical_crossentropy, optimizer=keras.optimizers.Adam(), metrics=['accuracy'])

In [3]:
# Part 2 - Fitting the CNN to the images

from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)
train_datagen

In [4]:
test_datagen = ImageDataGenerator(rescale = 1./255)
test_datagen

In [5]:
training_set = train_datagen.flow_from_directory('E:/Parent1', target_size = (28,28),
                                                 batch_size=128,
                                                 class_mode='categorical')
training_set

Found 40 images belonging to 4 classes.


In [6]:
test_set = test_datagen.flow_from_directory('E:/Parent1',
                                            target_size = (28,28),
                                            batch_size =128,
                                            class_mode = 'categorical')
test_set

Found 40 images belonging to 4 classes.


In [7]:
model.fit(training_set,epochs=2,steps_per_epoch = 250, verbose=1, validation_data=test_set)


Epoch 1/2
250/250 [==============================] - 1074s 4s/step - loss: 0.2124 - accuracy: 0.9413 - val_loss: 0.0011 - val_accuracy: 1.0000
Epoch 2/2
250/250 [==============================] - 1020s 4s/step - loss: 0.0017 - accuracy: 1.0000 - val_loss: 2.6834e-04 - val_accuracy: 1.0000


In [8]:
score = model.evaluate(test_set)
print('Test Loss:', score[0])
print('Test accuracy:', score[1])

1/1 [==============================] - 6s 6s/step
Test Loss: 0.00026834331220015883
Test accuracy: 1.0


In [9]:
model.save("Multiple Class Image with LeNet.h5")
print("Saved model to disk")

Saved model to disk


In [10]:
# Part 3 - Making new predictions
import numpy as np
from keras.preprocessing import image
test_image = image.load_img(r'C:\Users\Abhishek Negi\Desktop\Pic\IMG-20190620-WA0030.jpg', target_size = (28,28))
test_image

In [11]:
test_image = image.img_to_array(test_image)
test_image

array([[[219., 234., 241.],
        [219., 234., 241.],
        [220., 233., 239.],
        ...,
        [217., 222., 225.],
        [211., 219., 221.],
        [208., 218., 220.]],

       [[216., 231., 238.],
        [218., 231., 237.],
        [221., 232., 236.],
        ...,
        [221., 226., 229.],
        [218., 223., 227.],
        [216., 224., 227.]],

       [[231., 239., 242.],
        [227., 236., 241.],
        [222., 233., 239.],
        ...,
        [223., 229., 229.],
        [221., 226., 229.],
        [221., 226., 230.]],

       ...,

       [[ 80.,  48.,  27.],
        [ 82.,  51.,  30.],
        [ 82.,  51.,  31.],
        ...,
        [105.,  72.,  55.],
        [107.,  72.,  53.],
        [107.,  74.,  59.]],

       [[100.,  63.,  47.],
        [113.,  77.,  61.],
        [102.,  65.,  47.],
        ...,
        [107.,  79.,  65.],
        [110.,  82.,  70.],
        [112.,  83.,  67.]],

       [[115.,  83.,  68.],
        [122.,  84.,  71.],
        [118.,  

In [12]:
test_image = np.expand_dims(test_image, axis = 0)
test_image

array([[[[219., 234., 241.],
         [219., 234., 241.],
         [220., 233., 239.],
         ...,
         [217., 222., 225.],
         [211., 219., 221.],
         [208., 218., 220.]],

        [[216., 231., 238.],
         [218., 231., 237.],
         [221., 232., 236.],
         ...,
         [221., 226., 229.],
         [218., 223., 227.],
         [216., 224., 227.]],

        [[231., 239., 242.],
         [227., 236., 241.],
         [222., 233., 239.],
         ...,
         [223., 229., 229.],
         [221., 226., 229.],
         [221., 226., 230.]],

        ...,

        [[ 80.,  48.,  27.],
         [ 82.,  51.,  30.],
         [ 82.,  51.,  31.],
         ...,
         [105.,  72.,  55.],
         [107.,  72.,  53.],
         [107.,  74.,  59.]],

        [[100.,  63.,  47.],
         [113.,  77.,  61.],
         [102.,  65.,  47.],
         ...,
         [107.,  79.,  65.],
         [110.,  82.,  70.],
         [112.,  83.,  67.]],

        [[115.,  83.,  68.],
       

In [13]:
from keras.models import load_model
model=load_model('Multiple Class Image with LeNet.h5')
result= model.predict(test_image)
result

array([[0., 0., 0., 1.]], dtype=float32)

In [14]:
training_set.class_indices

{'Abhishek Negi': 0, 'Chennu': 1, 'Dorami': 2, 'Rinki': 3}

In [15]:
if result[0][0] == 1:
    prediction = 'Abhishek Negi'
    print(prediction)
elif result[0][1]==1:
    prediction = 'Cheenu'
    print(prediction)
elif result[0][2]==1:
    prediction = 'Dorami'
    print(prediction)
elif result[0][3]==1:
    prediction = 'Rinki'
    print(prediction)
else:
    print('Not Predicted')

Rinki


In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 24, 24, 6)         456       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 12, 12, 6)         0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 8, 8, 16)          2416      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 4, 4, 16)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 256)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 120)               30840     
_________________________________________________________________
dense_2 (Dense)              (None, 84)               